[versions]
gradle = "8.13.0"
jitsiMeetSdk = "11.6.1"
kotlin = "2.2.0"
navigationSafeArgs = "2.9.5"
preferenceKtx = "1.2.1"

[libraries]
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
jitsi-meet-sdk = { module = "org.jitsi.react:jitsi-meet-sdk", version.ref = "jitsiMeetSdk" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }

[plugins]
android-application = { id = "com.android.application" }
androidx-navigation-safeargs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigationSafeArgs" }
kotlin-android = { id = "kotlin-android" }
